config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio', as: :portfolio
  get '/welcome' => 'pages#welcome', as: :welcome
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome

  end

  def portfolio
    
  end

  def about 

  end

  def contact

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <h2>Kristina Radojevic</h2>
    <div class="topnav">
      <a class="active" href="#home"><%= link_to "Welcome", welcome_path %></a>
      <a href="#news"><%= link_to "Portfolio", portfolio_path %></a>
      <a href="#news"><%= link_to "About", about_path %></a>
      <a href="#news"><%= link_to "Contact", contact_path %></a>
    </div>
  </header>
<%= yield %>
<footer class="footer">
    <a href="https://github.com/kristinaradojevic">github</a>
  </footer>
</body>
</html>

app/views/pages/about.html.erb
<html>
  <body>
    <h2> About page </h2>
  <body>
</html>

app/views/pages/contact.html.erb
<html>

<body>

  <main >
    <ul>
      <li>Email</li>
      <li>Facebook</li>
      <li>GitHub</li>
      <li>LinkedIn</li>
      <li>Twitter</li>
    </ul>
  </main>
  
</body>

</html>

app/views/pages/portfolio.html.erb
<html>

<body>

</body>

</html>

app/views/pages/welcome.html.erb
<html>

<body>

  <main class="main">
    <h4>I am a programmer </h4>
    <button type="button">View my Work</button>
  </main>
  
</body>

</html>